wandb_version: 1

env:
  desc: null
  value: reacher
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717322308
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
